
default: &default
  adapter: postgresql
  encoding: unicode
  username: "postgres"
  password: "hamza"
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Blog_app_development

test:
  <<: *default
  database: Blog_app_test
production:
  <<: *default
  database: Blog_app_production

